### ISSUE TITLE
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp,

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [ironmansoftware/code-conversion#1]
Hello,

I am unable to use the ConvertTo-PowerShell command with the 'CSharpFile' parameter.
It returns an error ConvertTo-PowerShell: Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' - The specified file could not be found.

![image](https://user-images.githubusercontent.com/44971529/164533244-a0a67450-79db-4bb4-a494-691b80a3a123.png)

I think the DLL should be in the repo.

Thank you.

Cordially,

Thomas.

**Comment by kyjdp** [comment]
I have the same problem

**Comment by buckyj** [comment]
Same problem.

**Comment by baltmann** [comment]
Going the other way ...
ConvertTo-CSharp : The type initializer for 'CodeConverter.PowerShell.CommandIntentFactory' threw an exception.
At line:3 char:1
+ ConvertTo-CSharp -PowerShellScript @"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-CSharp], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,PowerShellToolsPro.Cmdlets.ConvertToCSharpCommand

**Comment by Excel-lent** [comment]
Same problem with Microsoft.CodeAnalysis.CSharp.
Copying of the dll to "c:\Program Files\WindowsPowerShell\Modules\CodeConversion\1.0.0\" didn't help.

**Comment by StingyJack** [comment]
The first problem is that the assembly isnt getting copied from the nuget lib to the bin folder.  I can add `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`  to the PropertyGroup in the CodeConversion.csproj and that will dump all the files needed into the bin/debug...  folder.  However that still throws the same FIleNotFound error when trying to debug 
![image](https://user-images.githubusercontent.com/15381181/170849004-5b00a116-d30e-449e-beca-260c337d4c79.png)

`System.Reflection.Assembly.GetExecutingAssembly()` has the right dll file. This probably needs an assembly resolver added to it or something.

**Comment by Jasonlhy** [comment]
> Same problem with Microsoft.CodeAnalysis.CSharp. Copying of the dll to "c:\Program Files\WindowsPowerShell\Modules\CodeConversion\1.0.0" didn't help.

Tried, same for me

**Comment by rgbav** [comment]
Same problem

**Comment by adamdriscoll** [comment]
I've converted this module into a console app (still can be installed as a module) to work around this issue. You can find updated usage instructions on the readme.
