### ISSUE TITLE
How to access via Visual Studio Code?

### ISSUE THREAD

**Issue by rokejulianlockhart** [ironmansoftware/code-conversion#4]
"http://youtube.com/watch?v=g_zJNGLjGqs&lc=UgxfR_d3swEtzbqaCyF4AaABAg" depicts utilization of this command via Visual Studio Code. How do I achieve this?

"https://www.powershellgallery.com/packages/CodeConversion" does not explain how to.

**Comment by adamdriscoll** [comment]
This functionality is no longer built into the VS Code extension.

**Comment by RokeJulianLockhart** [comment]
@adamdriscoll, why is that?
